name: Check

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    name: Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: nixbuild/nix-quick-install-action@v33
        with:
          nix_conf: |
            extra-substituters = https://codex-desktop-linux.cachix.org https://codex-cli.cachix.org https://ghostty.cachix.org https://hyprland.cachix.org https://nix-gaming.cachix.org https://noctalia.cachix.org https://vicinae.cachix.org https://niri.cachix.org https://nix-community.cachix.org https://cachix.cachix.org
            extra-trusted-public-keys = codex-desktop-linux.cachix.org-1:nX/xy6AdK9hQE24A8ALGjkCKj2ObFmcnemiL5Cid4nk= codex-cli.cachix.org-1:1Br3H1hHoRYG22n//cGKJOk3cQXgYobUel6O8DgSing= ghostty.cachix.org-1:QB389yTa6gTyneehvqG58y0WnHjQOqgnA+wBnpWWxns= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4= vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc= niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=

      - name: Check Nix lint
        run: nix build --print-build-logs .#checks.x86_64-linux.statix

      - name: Evaluate nix-darwin configuration
        run: nix eval .#darwinConfigurations.macbook-pro.system --raw
